#!/bin/bash
# Copyright (c) 2019 by Audere
#
# Use of this source code is governed by an LGPL-3.0 license that
# can be found in the LICENSE file distributed with this file.
set -euo pipefail

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"
source "$REPO_ROOT_DIR/scripts/build-hacks"
do_FluStudy_hacks Covid19_Antibody_uk
